### ISSUE TITLE
好像不能用

### ISSUE THREAD

**Issue by hyp530** [canc3s/cSubsidiary#1]
随便试下 go run cSubsidiary.go -i 2349319536  ， 它是有一家子公司的，但获取不出来。但ReadMe中的案例“字节跳动”是可以的。

**Comment by canc3s** [comment]
因为默认显示投资比例为x以上的公司 (default 100)和显示投资资金为x万以上的公司 (default 100)

<img width="932" alt="image" src="https://user-images.githubusercontent.com/36873866/117611198-a74cbe00-b195-11eb-9993-f3056e74a5ff.png">
你可以试试 `-i 2349319536 -p 0 -w 0`
