### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by jinzezhi** [canc3s/cSubsidiary#10]
![image](https://user-images.githubusercontent.com/93123422/229744538-909f296b-c19d-49dc-8d8d-8998ac9eafd6.png)
ping不通，是不是天眼查换域名了呀

**Comment by canc3s** [comment]
你应该是下载的releases吧，源码部分已经更新接口了，可以下载源吗编译一下

**Comment by nzfish** [comment]
> 你应该是下载的releases吧，源码部分已经更新接口了，可以下载源吗编译一下

请问大佬能指导一下如何修改接口吗？

**Comment by canc3s** [comment]
> > 你应该是下载的releases吧，源码部分已经更新接口了，可以下载源吗编译一下
> 
> 请问大佬能指导一下如何修改接口吗？

请求接口大部分都在 https://github.com/canc3s/cSubsidiary/blob/main/internal/runner/requests.go 里面，可以自己修改里面的函数
