### ISSUE TITLE
无法获得查询结果

### ISSUE THREAD

**Issue by Answerfxy** [canc3s/cSubsidiary#3]
您好，请问为什么我无法获得查询结果？情况如下图：

<img width="869" alt="image" src="https://user-images.githubusercontent.com/22865374/153810985-2746abc3-dbbb-4d07-9a86-c945b7a51450.png">

**Comment by canc3s** [comment]
因为官网发生了变化导致规则匹配不上，已经修复了

**Comment by Answerfxy** [comment]
> 

谢谢您啦！

**Comment by Answerfxy** [comment]
不好意思，还有一个问题想请教您。
我设置了网站的cookie，但仍然显示”天眼查Cookie有问题或过期，请重新获取“，是我添加cookie的方式有问题吗？
<img width="603" alt="image" src="https://user-images.githubusercontent.com/22865374/154011289-49859b77-3ae5-4206-a7e0-fb264c58c66b.png">

**Comment by canc3s** [comment]
bash中应该用$Cookie，%Cookie%是Windows中变量的表示方法，你改一下试试
