### ISSUE TITLE
cannot find package "github.com/canc3s/cSubsidiary/internal/runner" in any of

### ISSUE THREAD

**Issue by fubostudy** [canc3s/cSubsidiary#5]
你好，作者，想问一下这个问题应该怎么解决呢？（不好意思，有点菜）

![image](https://user-images.githubusercontent.com/49436908/160234395-f0378e36-d77b-4b1a-9397-ac283e0f0c91.png)

**Comment by fubostudy** [comment]
作者，我下载了64位的win exe程序运行也直接闪退了，求助，感谢啊🙏

**Comment by canc3s** [comment]
这个是go环境有问题，导致没找到包，所以没运行成功。可以检查一下golang的环境或者具体说一下环境。

```
git clone https://github.com/canc3s/cSubsidiary.git

 cd cSubsidiary/cmd/cSubsidiary

go run cSubsidiary.go -h
```
正常环境下，这三个命令按顺序执行就可以正常使用

**Comment by fubostudy** [comment]
作者，你说的对。我之前没有配置过go环境，刚刚配置了一下路径已经运行成功了。但是运行成功后,没有查询到信息。我刚开始运行，应该没有触发多次查询。代理ip也已经关闭了。看issues说之前的查询端口已经修复了，想请问一下这可能是什么原因呢？不好意思啊，我太菜了...谢谢啊🙏

![image](https://user-images.githubusercontent.com/49436908/160343019-67199942-6c10-4753-a218-ee305a60c10e.png)

![image](https://user-images.githubusercontent.com/49436908/160343067-e6230e54-9a12-4e7f-9fb0-270b72a5ee35.png)

**Comment by fubostudy** [comment]
谢谢啊，我mac安装的是go@18.我卸载安装了17 还是不行。可以问问您用的是什么版本吗？

**Comment by canc3s** [comment]
我用的的是1.17.1，代码能跑起来就和golang版本没关系了，应该是代码或者网络的原因。可以是重新clone一下代码试试

**Comment by fubostudy** [comment]
作者，我今天又试了几下，最后就运行成功了，感谢啦！
