### ISSUE TITLE
查询失败

### ISSUE THREAD

**Issue by TryA9ain** [canc3s/cSubsidiary#6]
<img width="957" alt="image" src="https://user-images.githubusercontent.com/51145610/162890613-c701e652-c556-4cff-86e8-1fdb7cfb9519.png">

**Comment by canc3s** [comment]
你应该是直接使用的releases里的版本吧，releases里的版本应该是不能用了，建议用源码重新编译一下

**Comment by TryA9ain** [comment]
> 你应该是直接使用的releases里的版本吧，releases里的版本应该是不能用了，建议用源码重新编译一下

<img width="190" alt="image" src="https://user-images.githubusercontent.com/51145610/162949750-06a03c8e-55b5-48c1-879f-d72877a5326b.png">
像这种已注销 100% 控股的子公司是查不到的吗？我测试是查不到的

**Comment by canc3s** [comment]
是的，我默认把注销的子公司做了过滤。详细代码在：
https://github.com/canc3s/cSubsidiary/blob/a86d355b09a64a6f0c48359ca871eaaeb6cf72b9/internal/runner/requests.go#L118
