### ISSUE TITLE
【更新建议】支持递归查询

### ISSUE THREAD

**Issue by 1979139113** [canc3s/cSubsidiary#9]
如我需要查询“抖音有限公司”，那么可以查询到子公司后继续查询子公司的子公司，相当于查询所有的实际控股，而不是每次只能查询当前公司的子公司。

<img width="1225" alt="图片" src="https://user-images.githubusercontent.com/24983597/219586788-c4519979-a131-4375-9123-afc82adf1e7b.png">

**Comment by canc3s** [comment]
递归查询子公司可以参考这篇文章：
https://canc3s.github.io/2021/03/01/

直接使用bash命令有很大的灵活性

**Comment by 1979139113** [comment]
谢谢师傅，我试了一下用shell脚本的方式来尝试一直获取，确实可以，效果也还不错

```bash
savePath=1.txt
tmpSaveName_1=2.txt
tmpSaveName_2=3.txt

# 第一次执行目标
cookie='x'
./cSubsidiary_linux_amd64 -c "$cookie" -n 北京游逸科技有限公司 -o $savePath

# 一直循环到没有子公司为止
cp $savePath $tmpSaveName_1
while true
do
    ./cSubsidiary_linux_amd64 -c "$cookie" -f $tmpSaveName_1 -o $tmpSaveName_2
    if [[ -s $tmpSaveName_2 ]];then
        cat $tmpSaveName_2 >> $savePath
        mv $tmpSaveName_2 $tmpSaveName_1
    else
        break
    fi
done
rm $tmpSaveName_1 $tmpSaveName_2
```

---

不过有个小问题，可以给大家参考下，像下图这种组合起来投资为100%的是没法提取的

<img width="1256" alt="图片" src="https://user-images.githubusercontent.com/24983597/219647839-d6ab67f4-97fa-4f10-ba02-1a3c02a90fb3.png">

我再研究一下，感谢师傅🙏
